### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by Timowest12** [Timowest12/JS-capstone#21]
We(Femi and I) set up this project according to project requirements:

- Set up project to use correct gitflow.
- Copied the Kanban board columns.
- Removed unneeded tasks for student C.
- Closed unneeded issues.
- Copied all Kanban tasks using bash script.
[Link to repo](https://github.com/Timowest12/JS-capstone)
[Link to Kanban board](https://github.com/Timowest12/JS-capstone/projects/1)

**Comment by carlos-ssh** [comment]
Hi @Timowest12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- Add a link to your kanban board.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timowest12** [comment]
Added link to Kanban board to Pull request.

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @Timowest12 &  @phelian23, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
